# Generated by Django 5.1.6 on 2025-03-06 10:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название города')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='название университета')),
                ('address', models.CharField(help_text='Формат: страна,город,улица,номер улицы', max_length=200, verbose_name='адрес университета')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=0, message='рейтинг не может быть отрицательным'), django.core.validators.MaxValueValidator(limit_value=5, message='рейтинг не может быть больше 5')], verbose_name='рейтинг')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university', to='main.city', verbose_name='город')),
            ],
            options={
                'verbose_name': 'университет',
                'verbose_name_plural': 'университеты',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст комментария')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания комментария')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата и время обновления')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=0, message='рейтинг не может быть отрицательным'), django.core.validators.MaxValueValidator(limit_value=5, message='рейтинг не может быть больше 5')], verbose_name='рейтинг')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='автор комментария')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='main.university', verbose_name='университет')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ('-id',),
            },
        ),
    ]
