# Generated by Django 5.1.6 on 2025-03-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Логотип'),
        ),
    ]
