# Generated by Django 5.1.6 on 2025-03-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_university_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Сайт'),
        ),
    ]
