# Generated by Django 5.1.6 on 2025-03-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_city_university_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='main.university', verbose_name='университет'),
        ),
    ]
